window.courseCatalog = [
  {
    id: 'premiere',
    title: 'Première · spécialité mathématiques',
    note: 'Programme en vigueur à la rentrée 2026-2027.',
    source: 'https://www.education.gouv.fr/bo/2026/Hebdo14/MENE2602917A',
    chapters: [
      { id: 'premiere-suites', title: 'Suites numériques', field: 'Algèbre', summary: 'Modéliser une évolution à partir de termes successifs ; reconnaître les suites arithmétiques et géométriques, calculer des termes et des sommes.', lesson: { sections: ['Une suite est une liste ordonnée de nombres notés u₀, u₁, u₂, ... ou u₁, u₂, ... selon l’indice de départ. Son indice n représente souvent le temps ou le rang d’une étape.', 'Une suite explicite donne directement uₙ en fonction de n. Une suite récurrente donne un premier terme et une règle pour calculer le suivant, par exemple uₙ₊₁ = uₙ + 4.'], formula: { label: 'TERMES ET SOMMES', text: 'Arithmétique : uₙ = u₀ + nr ; Sₙ = (n + 1)(u₀ + uₙ)/2  |  Géométrique : vₙ = v₀qⁿ' }, example: { statement: 'Une suite arithmétique commence à u₀ = 4 et augmente de 3 à chaque rang. Calculer u₅ et la somme de u₀ à u₅.', calculation: 'u₅ = 4 + 5 × 3 = 19. Il y a 6 termes, donc S = 6 × (4 + 19) / 2.', answer: 'u₅ = 19 et S = 69.' }, exercise: { question: 'Une suite géométrique vérifie v₀ = 80 et vₙ₊₁ = 0,5vₙ. Calculer v₃.', answer: 'v₃ = 80 × 0,5³ = 80 × 0,125 = 10.' } } },
      { id: 'second-degre', title: 'Équations et inéquations du second degré', field: 'Algèbre', page: 'index.html', summary: 'Forme développée, discriminant, racines, factorisation, signe et lien entre le trinôme et sa parabole.' },
      { id: 'premiere-derivee-locale', title: 'Dérivation : point de vue local', field: 'Analyse', summary: 'Taux de variation, nombre dérivé, tangente et approximation affine au voisinage d’un point.', lesson: { sections: ['Le taux de variation entre a et a + h est le quotient [f(a+h) − f(a)]/h. Lorsque h se rapproche de 0, si ce quotient tend vers un réel, sa limite est le nombre dérivé f′(a).', 'Géométriquement, f′(a) est la pente de la tangente à la courbe au point d’abscisse a. Il permet aussi d’approcher f(a+h) lorsque h est petit.'], formula: { label: 'NOMBRE DÉRIVÉ ET APPROXIMATION LOCALE', text: 'f′(a) = limₕ→₀ [f(a+h) − f(a)]/h  |  f(a+h) ≈ f(a) + hf′(a)' }, example: { statement: 'Pour f(x) = x², calculer f′(3) puis l’équation de la tangente en x = 3.', calculation: 'f′(x) = 2x, donc f′(3) = 6 et f(3) = 9. La tangente est y = 6(x − 3) + 9.', answer: 'La pente vaut 6 et la tangente a pour équation y = 6x − 9.' }, exercise: { question: 'Pour f(x) = x² + 1, donner la pente de la tangente en x = 2.', answer: 'f′(x) = 2x, donc f′(2) = 4.' } } },
      { id: 'premiere-derivee-variations', title: 'Dérivation : applications et variations', field: 'Analyse', summary: 'Dérivées usuelles, opérations, signe de la dérivée, variations, extremums et optimisation.', lesson: { sections: ['Le signe de f′ indique les variations de f : une dérivée positive correspond à une fonction croissante, une dérivée négative à une fonction décroissante.', 'Si le signe de f′ passe de − à +, la fonction atteint un minimum local. S’il passe de + à −, elle atteint un maximum local. Une dérivée nulle seule ne suffit pas à conclure.'], formula: { label: 'LIEN ENTRE DÉRIVÉE ET VARIATIONS', text: 'f′ > 0 ⇒ f croît  |  f′ < 0 ⇒ f décroît' }, example: { statement: 'Étudier les variations de f(x) = x² − 4x + 1.', calculation: 'f′(x) = 2x − 4 = 2(x − 2). Elle est négative avant 2, nulle en 2 et positive après 2. f(2) = −3.', answer: 'f décroît puis croît ; son minimum vaut −3 en x = 2.' }, exercise: { question: 'Étudier les variations de g(x) = x² − 6x + 8.', answer: 'g′(x) = 2(x − 3) : g décroît jusqu’à 3 puis croît. Son minimum est g(3) = −1.' } } },
      { id: 'premiere-exponentielle', title: 'Fonction exponentielle', field: 'Analyse', summary: 'Définition et propriétés de la fonction exponentielle, nombre e, croissance et dérivée.', lesson: { sections: ['La fonction exponentielle, notée exp, est l’unique fonction dérivable qui vérifie (eˣ)′ = eˣ et e⁰ = 1. On note e = e¹, avec e environ égal à 2,718.', 'Elle est strictement positive et strictement croissante. Elle transforme une somme en produit, ce qui la rend utile pour modéliser une croissance proportionnelle.'], formula: { label: 'PROPRIÉTÉS ET DÉRIVÉE', text: 'eᵃ⁺ᵇ = eᵃeᵇ  |  e⁻ᵃ = 1/eᵃ  |  (eˣ)′ = eˣ' }, example: { statement: 'Étudier les variations de f(x) = eˣ − 2x.', calculation: 'f′(x) = eˣ − 2. Il existe un unique nombre α tel que e^α = 2. La dérivée est négative avant α, puis positive après.', answer: 'f décroît jusqu’à α, puis croît. Elle atteint son minimum en α.' }, exercise: { question: 'Dériver g(x) = 3e²ˣ.', answer: 'La dérivée de e²ˣ est 2e²ˣ. Donc g′(x) = 3 × 2e²ˣ = 6e²ˣ.' } } },
      { id: 'premiere-trigonometrie', title: 'Trigonométrie', field: 'Analyse', summary: 'Cercle trigonométrique, radian, cosinus, sinus et valeurs remarquables.', lesson: { sections: ['Sur le cercle trigonométrique de rayon 1, l’angle est mesuré en radians. À l’angle x correspond le point de coordonnées (cos x ; sin x). Le sens positif est le sens inverse des aiguilles d’une montre.', 'Un tour complet mesure 2π radians et un demi-tour π. Les coordonnées du cercle donnent immédiatement les valeurs de cos et sin pour les angles usuels.'], formula: { label: 'IDENTITÉ FONDAMENTALE', text: 'cos²(x) + sin²(x) = 1  |  180° = π radians' }, example: { statement: 'Résoudre cos(x) = 1/2 sur l’intervalle [0 ; 2π].', calculation: 'Sur le cercle, l’abscisse vaut 1/2 aux angles π/3 et 5π/3.', answer: 'Les solutions sont x = π/3 et x = 5π/3.' }, exercise: { question: 'Donner les valeurs de cos(π/6) et sin(π/6).', answer: 'Sur le cercle trigonométrique, cos(π/6) = √3/2 et sin(π/6) = 1/2.' } } },
      { id: 'premiere-produit-scalaire', title: 'Calcul vectoriel et produit scalaire', field: 'Géométrie', summary: 'Projection orthogonale, angle entre vecteurs, bilinéarité et calculs dans une base orthonormée.', lesson: { sections: ['Le produit scalaire de deux vecteurs mesure leur alignement. Il est positif si l’angle est aigu, nul s’ils sont perpendiculaires, et négatif si l’angle est obtus.', 'Dans un repère orthonormé, on peut calculer le produit scalaire avec les coordonnées. Cette méthode est souvent plus rapide que de calculer une longueur ou un angle.'], formula: { label: 'DEUX FORMULES À CONNAÎTRE', text: 'u · v = ||u|| ||v|| cos(θ)  |  (x ; y) · (x′ ; y′) = xx′ + yy′' }, example: { statement: 'Les vecteurs u = (3 ; 1) et v = (2 ; −6) sont-ils perpendiculaires ?', calculation: 'u · v = 3 × 2 + 1 × (−6) = 6 − 6 = 0.', answer: 'Le produit scalaire est nul : les deux vecteurs sont orthogonaux.' }, exercise: { question: 'Calculer le produit scalaire de a = (1 ; 4) et b = (2 ; 3).', answer: 'a · b = 1 × 2 + 4 × 3 = 14.' } } },
      { id: 'premiere-geometrie-reperee', title: 'Géométrie repérée', field: 'Géométrie', summary: 'Vecteur normal à une droite, équation de cercle et projection orthogonale.', lesson: { sections: ['Une équation cartésienne de droite s’écrit ax + by + c = 0. Le vecteur n = (a ; b) est normal à la droite : il lui est perpendiculaire.', 'Un cercle de centre Ω(h ; k) et de rayon r regroupe les points M(x ; y) dont la distance à Ω vaut r. La formule de distance donne directement son équation.'], formula: { label: 'ÉQUATIONS REPÉRÉES', text: 'Droite : ax + by + c = 0  |  Cercle : (x − h)² + (y − k)² = r²' }, example: { statement: 'Écrire l’équation du cercle de centre Ω(1 ; −2) et de rayon 3.', calculation: 'On remplace h par 1, k par −2 et r par 3 dans la formule du cercle.', answer: '(x − 1)² + (y + 2)² = 9.' }, exercise: { question: 'Donner un vecteur normal à la droite 2x − 3y + 5 = 0.', answer: 'Les coefficients de x et y donnent le vecteur normal n = (2 ; −3).' } } },
      { id: 'premiere-probabilites-conditionnelles', title: 'Probabilités conditionnelles et indépendance', field: 'Probabilités', summary: 'Conditionnement, indépendance, formule des probabilités totales et répétition d’épreuves.', lesson: { sections: ['La probabilité de B sachant A se note P_A(B). Elle décrit la probabilité de B lorsqu’on sait déjà que A est réalisé. Dans un arbre, on multiplie les probabilités le long d’une branche.', 'Deux événements A et B sont indépendants si le fait de connaître la réalisation de l’un ne change pas la probabilité de l’autre. Un arbre pondéré aide à organiser les cas et à totaliser les probabilités.'], formula: { label: 'CONDITIONNEMENT, INDÉPENDANCE ET TOTALES', text: 'P_A(B) = P(A ∩ B) / P(A)  |  Indépendance : P(A ∩ B) = P(A)P(B)  |  P(B) = P(A)P_A(B) + P(non A)P_non A(B)' }, example: { statement: 'Une usine produit 60 % des pièces sur A avec 2 % de défauts, et le reste sur B avec 5 % de défauts. Quelle est la proportion totale de défauts ?', calculation: 'P(D) = 0,60 × 0,02 + 0,40 × 0,05 = 0,012 + 0,020.', answer: '3,2 % des pièces sont défectueuses.' }, exercise: { question: 'Avec ces données, calculer la probabilité qu’une pièce défectueuse vienne de A.', answer: 'P(A sachant D) = P(A ∩ D)/P(D) = 0,012/0,032 = 0,375, soit 37,5 %.' } } },
      { id: 'premiere-variables-aleatoires', title: 'Variables aléatoires réelles', field: 'Probabilités', summary: 'Loi, espérance, variance, écart-type et interprétation de ces indicateurs.', lesson: { sections: ['Une variable aléatoire associe un nombre à chaque issue d’une expérience. Sa loi donne les valeurs possibles et la probabilité de chacune ; la somme des probabilités vaut 1.', 'L’espérance représente une moyenne théorique à long terme. La variance et l’écart-type mesurent la dispersion autour de cette moyenne.'], formula: { label: 'ESPÉRANCE ET VARIANCE', text: 'E(X) = Σ xᵢpᵢ  |  V(X) = Σ (xᵢ − E(X))²pᵢ  |  σ(X) = √V(X)' }, example: { statement: 'On lance un dé équilibré à six faces. Calculer son espérance.', calculation: 'Chaque valeur de 1 à 6 a la probabilité 1/6 : E(X) = (1 + 2 + 3 + 4 + 5 + 6)/6.', answer: 'E(X) = 3,5.' }, exercise: { question: 'Une variable vaut 0 avec probabilité 0,7 et 10 avec probabilité 0,3. Calculer son espérance.', answer: 'E(X) = 0 × 0,7 + 10 × 0,3 = 3.' } } },
      { id: 'premiere-echantillonnage', title: 'Échantillonnage et simulation', field: 'Probabilités', summary: 'Simuler une expérience, étudier une fréquence et interpréter la fluctuation d’échantillonnage.', lesson: { sections: ['Une fréquence observée dans un échantillon varie d’un échantillon à l’autre, même si la probabilité théorique p reste la même. Plus la taille n de l’échantillon augmente, plus la fréquence tend à se rapprocher de p.', 'Une simulation informatique répète l’expérience un grand nombre de fois. Elle aide à observer cette fluctuation, mais ne remplace pas une justification mathématique.'], formula: { label: 'ORDRE DE GRANDEUR DE LA FLUCTUATION', text: 'Écart-type de la fréquence : σ = √(p(1 − p) / n)' }, example: { statement: 'Une pièce équilibrée est lancée 100 fois. Quelle est l’échelle de variation attendue de la fréquence de piles ?', calculation: 'p = 0,5 et n = 100, donc σ = √(0,5 × 0,5 / 100) = 0,05. Deux écarts-types valent environ 0,10.', answer: 'Une fréquence proche de 0,5, souvent entre 0,4 et 0,6, est cohérente avec ce modèle.' }, exercise: { question: 'Pour p = 0,4 et n = 100, calculer l’écart-type de la fréquence.', answer: 'σ = √(0,4 × 0,6 / 100) ≈ 0,049.' } } }
    ]
  },
  {
    id: 'terminale',
    title: 'Terminale · spécialité mathématiques',
    note: 'Programme 2019 en vigueur en 2026-2027 ; nouveau programme à partir de 2027-2028.',
    source: 'https://www.education.gouv.fr/bo/19/Special8/MENE1921246A.htm',
    chapters: [
      { id: 'terminale-denombrement', title: 'Combinatoire et dénombrement', field: 'Algèbre et géométrie', summary: 'Principes additif et multiplicatif, arrangements, combinaisons, factorielle et triangle de Pascal.', lesson: { sections: ['Le principe additif sert à compter des choix incompatibles : on additionne leurs nombres de possibilités. Le principe multiplicatif sert aux choix successifs : on multiplie les nombres de possibilités à chaque étape.', 'Choisir k objets parmi n sans tenir compte de l’ordre se compte avec un coefficient binomial. Ne confonds pas ce choix avec un arrangement, où l’ordre compte.'], formula: { label: 'COMBINAISONS', text: 'C(n, k) = n! / (k!(n − k)!)' }, example: { statement: 'Combien de comités de 3 personnes peut-on former avec 8 candidats ?', calculation: 'L’ordre des personnes dans le comité ne compte. On calcule C(8, 3) = 8 × 7 × 6 / (3 × 2 × 1).', answer: 'Il existe 56 comités.' }, exercise: { question: 'Combien de paires distinctes peut-on choisir parmi 10 personnes ?', answer: 'L’ordre ne compte : C(10, 2) = 10 × 9 / 2 = 45 paires.' } } },
      { id: 'terminale-vecteurs-espace', title: 'Vecteurs, droites et plans de l’espace', field: 'Algèbre et géométrie', summary: 'Combinaisons linéaires, bases, repères et positions relatives dans l’espace.', lesson: { sections: ['Dans l’espace, un vecteur se décrit par trois coordonnées. Une droite est définie par un point et un vecteur directeur ; un plan peut être décrit par un point et deux directions non colinéaires.', 'Les combinaisons linéaires permettent de tester l’alignement ou la coplanarité et de comparer les directions.'], formula: { label: 'DROITE PARAMÉTRIQUE', text: 'M = A + t u, avec t ∈ ℝ' }, example: { statement: 'Écrire une représentation paramétrique de la droite passant par A(1 ; 0 ; 2) et dirigée par u = (2 ; −1 ; 3).', calculation: 'On ajoute à A un multiple t du vecteur directeur : (x ; y ; z) = (1 ; 0 ; 2) + t(2 ; −1 ; 3).', answer: 'x = 1 + 2t, y = −t, z = 2 + 3t, avec t réel.' }, exercise: { question: 'Donner un vecteur directeur de la droite x = 3 − t, y = 2 + 4t, z = 5t.', answer: 'Les coefficients de t donnent le vecteur directeur (−1 ; 4 ; 5).' } } },