window.courseCatalog = [
  {
    id: 'mecanique', title: 'Mécanique', note: 'Décrire le mouvement, ses causes et les échanges d’énergie.',
    chapters: [
      { id: 'cinematique', title: 'Cinématique du point', field: 'Classique · bases', summary: 'Position, vitesse et accélération en une et plusieurs dimensions.', lesson: { sections: ['La cinématique décrit un mouvement sans chercher ses causes. On choisit un référentiel, une origine des dates et un repère ; la position devient alors une fonction du temps.', 'La vitesse est la dérivée de la position et l’accélération la dérivée de la vitesse. En mouvement rectiligne uniformément accéléré, l’accélération est constante.'], formula: { label: 'MOUVEMENT À ACCÉLÉRATION CONSTANTE', text: 'v(t) = v₀ + at  |  x(t) = x₀ + v₀t + ½at²' }, example: { statement: 'Un véhicule part du repos et accélère à 2 m·s⁻² pendant 5 s. Quelle distance parcourt-il ?', calculation: 'Avec v₀ = 0 et x₀ = 0, x(5) = ½ × 2 × 5².', answer: 'Il parcourt 25 m.' }, exercise: { question: 'Un objet a v₀ = 3 m·s⁻¹ et a = 2 m·s⁻² pendant 4 s. Quelle est sa vitesse finale ?', answer: 'v = 3 + 2 × 4 = 11 m·s⁻¹.' } } },
      { id: 'lois-newton', title: 'Lois de Newton et forces', field: 'Classique · bases', summary: 'Bilan des forces, inertie, dynamique et action-réaction.', lesson: { sections: ['Une force modélise une interaction. Pour étudier un objet, on isole le système, on dresse le bilan des forces extérieures puis on applique la deuxième loi de Newton.', 'Dans un référentiel galiléen, la somme vectorielle des forces détermine l’accélération. Si la résultante est nulle, la vitesse reste constante : c’est le principe d’inertie.'], formula: { label: 'DEUXIÈME LOI DE NEWTON', text: 'ΣF⃗ext = m a⃗' }, example: { statement: 'Une masse de 4 kg subit une force horizontale résultante de 12 N. Quelle est son accélération ?', calculation: 'a = F/m = 12/4.', answer: 'a = 3 m·s⁻² dans la direction de la résultante.' }, exercise: { question: 'Quelle résultante faut-il pour accélérer une masse de 2 kg à 5 m·s⁻² ?', answer: 'F = ma = 2 × 5 = 10 N.' } } },
      { id: 'energie-mecanique', title: 'Travail, énergie et puissance', field: 'Classique · intermédiaire', summary: 'Travail d’une force, énergie cinétique, potentielle et conservation.', lesson: { sections: ['L’énergie cinétique dépend de la masse et de la vitesse. Le travail d’une force mesure le transfert d’énergie associé à un déplacement.', 'Le théorème de l’énergie cinétique relie la variation d’énergie cinétique au travail total des forces. En l’absence de dissipation, l’énergie mécanique se conserve.'], formula: { label: 'ÉNERGIES ET THÉORÈME', text: 'Ec = ½mv²  |  ΔEc = ΣW(F)  |  Em = Ec + Ep' }, example: { statement: 'Un objet de 2 kg passe de 3 à 5 m·s⁻¹. Quelle est la variation de son énergie cinétique ?', calculation: 'ΔEc = ½ × 2 × (5² − 3²) = 25 − 9.', answer: 'ΔEc = 16 J.' }, exercise: { question: 'Calculer Ec pour m = 0,5 kg et v = 4 m·s⁻¹.', answer: 'Ec = ½ × 0,5 × 4² = 4 J.' } } }
    ]
  },
  {
    id: 'thermodynamique', title: 'Thermodynamique', note: 'Relier température, énergie, chaleur et transformations.',
    chapters: [
      { id: 'gaz-parfaits', title: 'Température et gaz parfaits', field: 'Thermique · bases', summary: 'État d’un gaz, pression, volume, température absolue et équation d’état.', lesson: { sections: ['Un gaz parfait est un modèle de particules ponctuelles sans interaction à distance, sauf lors des collisions. Son état macroscopique est décrit par la pression P, le volume V, la température absolue T et la quantité de matière n.', 'La température dans l’équation d’état s’exprime en kelvins. Une hausse de température à volume constant augmente la pression ; une hausse de volume à température constante la diminue.'], formula: { label: 'ÉQUATION D’ÉTAT DU GAZ PARFAIT', text: 'PV = nRT  |  T(K) = θ(°C) + 273,15' }, example: { statement: '1 mol de gaz parfait occupe 24,0 L à 300 K. Estimer sa pression avec R = 8,314 J·mol⁻¹·K⁻¹.', calculation: 'P = nRT/V = 1 × 8,314 × 300 / 0,024.', answer: 'P ≈ 1,04 × 10⁵ Pa.' }, exercise: { question: 'Convertir 20 °C en kelvins.', answer: 'T = 20 + 273,15 = 293,15 K.' } } },
      { id: 'premier-principe', title: 'Premier principe et bilans d’énergie', field: 'Thermique · intermédiaire', summary: 'Énergie interne, chaleur, travail reçu et transformations.', lesson: { sections: ['Le premier principe exprime la conservation de l’énergie pour un système thermodynamique. La variation d’énergie interne est égale aux transferts reçus sous forme de chaleur et de travail.', 'Il faut annoncer clairement la convention de signe utilisée. Ici, Q et W sont positifs lorsque le système reçoit de l’énergie.'], formula: { label: 'PREMIER PRINCIPE', text: 'ΔU = Q + W' }, example: { statement: 'Un système reçoit 500 J de chaleur et fournit 120 J de travail au milieu extérieur. Quelle est la variation de son énergie interne ?', calculation: 'Q = +500 J. Comme le système fournit le travail, W = −120 J. Donc ΔU = 500 − 120.', answer: 'ΔU = +380 J.' }, exercise: { question: 'Un système reçoit 200 J de travail et perd 50 J de chaleur. Calculer ΔU.', answer: 'ΔU = Q + W = −50 + 200 = +150 J.' } } },
      { id: 'second-principe', title: 'Entropie et second principe', field: 'Thermique · approfondissement', summary: 'Sens d’évolution spontanée, irréversibilité et entropie.', lesson: { sections: ['Le premier principe conserve l’énergie mais ne donne pas le sens d’une évolution. Le second principe introduit l’entropie, une grandeur d’état qui quantifie la dispersion de l’énergie.', 'Pour un système isolé, l’entropie totale ne diminue pas : elle reste constante dans une transformation réversible idéale et augmente dans une transformation irréversible.'], formula: { label: 'BILAN D’ENTROPIE D’UN SYSTÈME ISOLÉ', text: 'ΔS ≥ 0  |  égalité : transformation réversible' }, example: { statement: 'Deux corps à températures différentes sont placés en contact dans un système isolé. Dans quel sens l’échange thermique se produit-il spontanément ?', calculation: 'La chaleur se transfère spontanément du corps le plus chaud vers le plus froid, jusqu’à l’équilibre thermique.', answer: 'L’entropie totale augmente ; le processus inverse ne se produit pas spontanément.' }, exercise: { question: 'Une transformation spontanée d’un système isolé peut-elle diminuer son entropie ?', answer: 'Non. Le second principe impose ΔS ≥ 0.' } } }
    ]
  },
  {
    id: 'electromagnetisme', title: 'Électricité et électromagnétisme', note: 'Des circuits électriques aux champs et à l’induction.',
    chapters: [
      { id: 'circuits-electriques', title: 'Circuits électriques', field: 'Électricité · bases', summary: 'Tension, courant, loi d’Ohm, puissance et associations de résistances.', lesson: { sections: ['Le courant électrique est un débit de charges. La tension entre deux points représente une différence d’énergie électrique par charge.', 'Pour un conducteur ohmique, la tension est proportionnelle au courant. La loi des nœuds traduit la conservation de la charge et la loi des mailles la conservation de l’énergie.'], formula: { label: 'LOI D’OHM ET PUISSANCE', text: 'U = RI  |  P = UI = RI²' }, example: { statement: 'Une résistance de 6 Ω est parcourue par un courant de 2 A. Calculer la tension et la puissance.', calculation: 'U = RI = 6 × 2 = 12 V. P = UI = 12 × 2.', answer: 'U = 12 V et P = 24 W.' }, exercise: { question: 'Quel courant traverse une résistance de 10 Ω sous 5 V ?', answer: 'I = U/R = 5/10 = 0,5 A.' } } },
      { id: 'champ-electrique', title: 'Électrostatique et champ électrique', field: 'Électromagnétisme · intermédiaire', summary: 'Charges, loi de Coulomb, champ et potentiel électrostatiques.', lesson: { sections: ['Deux charges électriques exercent l’une sur l’autre une force. Des charges de même signe se repoussent et de signes opposés s’attirent.', 'Le champ électrique décrit la force par unité de charge positive. Le potentiel électrique est une énergie potentielle par unité de charge.'], formula: { label: 'FORCE DE COULOMB ET CHAMP', text: 'F = k|q₁q₂|/r²  |  E⃗ = F⃗/q' }, example: { statement: 'Une charge de 2 μC est placée dans un champ électrique uniforme de 300 N·C⁻¹. Quelle force électrique subit-elle ?', calculation: 'F = qE = 2 × 10⁻⁶ × 300.', answer: 'F = 6 × 10⁻⁴ N, dans le sens du champ si la charge est positive.' }, exercise: { question: 'Quelle force subit une charge −1 μC dans un champ de 200 N·C⁻¹ ?', answer: 'La norme vaut 2 × 10⁻⁴ N ; la force est opposée au champ car la charge est négative.' } } },
      { id: 'induction', title: 'Magnétisme et induction', field: 'Électromagnétisme · approfondissement', summary: 'Champ magnétique, flux, loi de Faraday-Lenz et applications.', lesson: { sections: ['Un courant électrique produit un champ magnétique. Un champ magnétique variable peut induire une tension dans un circuit.', 'La loi de Lenz fixe le sens du courant induit : ses effets s’opposent à la variation de flux qui lui donne naissance.'], formula: { label: 'LOI DE FARADAY', text: 'e = −dΦ/dt' }, example: { statement: 'Le flux magnétique à travers une bobine augmente de 0,04 Wb en 0,02 s. Quelle est la valeur absolue de la tension induite moyenne ?', calculation: '|e| = |ΔΦ/Δt| = 0,04/0,02.', answer: '|e| = 2 V ; son signe dépend du sens choisi et s’oppose à la variation.' }, exercise: { question: 'Que se passe-t-il si le flux magnétique reste constant ?', answer: 'dΦ/dt = 0 : aucune tension induite n’est produite.' } } }
    ]
  },
  {
    id: 'ondes-acoustique', title: 'Ondes et acoustique', note: 'Propagation, superposition et phénomènes ondulatoires.',
    chapters: [
      { id: 'oscillations', title: 'Oscillations et signaux périodiques', field: 'Ondes · bases', summary: 'Période, fréquence, amplitude, phase et oscillateur harmonique.', lesson: { sections: ['Un signal périodique se répète après une durée T, sa période. La fréquence f compte le nombre de périodes par seconde et s’exprime en hertz.', 'Un oscillateur harmonique idéal suit une évolution sinusoïdale. Sa fréquence dépend des paramètres du système, comme la masse et la raideur pour un ressort.'], formula: { label: 'PÉRIODE ET FRÉQUENCE', text: 'f = 1/T  |  x(t) = A cos(ωt + φ), avec ω = 2πf' }, example: { statement: 'Un signal a une période de 4 ms. Quelle est sa fréquence ?', calculation: 'T = 0,004 s, donc f = 1/0,004.', answer: 'f = 250 Hz.' }, exercise: { question: 'Quelle est la période d’un signal de fréquence 500 Hz ?', answer: 'T = 1/500 = 0,002 s, soit 2 ms.' } } },
      { id: 'interferences', title: 'Interférences et diffraction', field: 'Ondes · intermédiaire', summary: 'Superposition, cohérence, franges et limite de résolution.', lesson: { sections: ['Lorsque deux ondes cohérentes se superposent, leurs amplitudes s’ajoutent. Selon leur déphasage, elles peuvent se renforcer ou s’annuler.', 'La diffraction est l’étalement d’une onde lorsqu’elle traverse une ouverture ou contourne un obstacle de taille comparable à sa longueur d’onde.'], formula: { label: 'INTERFRANGE ET DIFFRACTION', text: 'i = λD/a  |  θ ≈ λ/a pour une petite ouverture' }, example: { statement: 'Dans une expérience à deux fentes, λ = 600 nm, D = 2 m et l’écartement vaut a = 0,5 mm. Calculer l’interfrange.', calculation: 'i = 600×10⁻⁹ × 2 / (0,5×10⁻³).', answer: 'i = 2,4 mm.' }, exercise: { question: 'Comment varie l’interfrange si la distance D à l’écran double ?', answer: 'Comme i est proportionnel à D, l’interfrange double.' } } },
      { id: 'acoustique', title: 'Acoustique et effet Doppler', field: 'Ondes · applications', summary: 'Son, intensité, niveau sonore et décalage Doppler.', lesson: { sections: ['Le son est une onde mécanique longitudinale : il a besoin d’un milieu matériel pour se propager. Sa fréquence détermine la hauteur perçue et son amplitude est liée à l’intensité.', 'L’effet Doppler est la variation apparente de fréquence lorsque source et observateur sont en mouvement l’un par rapport à l’autre.'], formula: { label: 'NIVEAU SONORE', text: 'L = 10 log₁₀(I/I₀) dB' }, example: { statement: 'L’intensité sonore vaut 10⁻⁶ W·m⁻² et I₀ = 10⁻¹² W·m⁻². Calculer le niveau sonore.', calculation: 'I/I₀ = 10⁶, donc L = 10 log₁₀(10⁶).', answer: 'L = 60 dB.' }, exercise: { question: 'De combien augmente le niveau sonore si l’intensité est multipliée par 10 ?', answer: 'Il augmente de 10 dB.' } } }
    ]
  },
  {
    id: 'optique', title: 'Optique', note: 'Former des images et comprendre la nature ondulatoire de la lumière.',
    chapters: [
      { id: 'optique-geometrique', title: 'Optique géométrique et lentilles', field: 'Optique · bases', summary: 'Rayons lumineux, lentilles minces, images réelles et virtuelles.', lesson: { sections: ['Dans l’approximation de Gauss, les rayons proches de l’axe optique sont peu inclinés ; une lentille mince forme alors une image construite par les rayons principaux.', 'Une image réelle peut être projetée sur un écran ; une image virtuelle est visible en regardant dans le système optique mais ne peut pas être recueillie directement sur un écran.'], formula: { label: 'RELATION DE CONJUGAISON', text: '1/OA′ − 1/OA = 1/OF′' }, example: { statement: 'Une lentille convergente a une distance focale f′ = 10 cm. Un objet est à 30 cm devant elle. Où se forme l’image ?', calculation: 'Avec OA = −30 cm : 1/OA′ = 1/10 − 1/(−30) = 4/30.', answer: 'OA′ = 7,5 cm derrière la lentille ; l’image est réelle.' }, exercise: { question: 'Où se forme l’image d’un objet placé au foyer objet d’une lentille convergente ?', answer: 'Les rayons émergent parallèlement : l’image est à l’infini.' } } },
      { id: 'refraction', title: 'Réflexion et réfraction', field: 'Optique · bases', summary: 'Lois de Snell-Descartes et changement de direction à une interface.', lesson: { sections: ['Lorsqu’un rayon lumineux rencontre une interface, une partie peut être réfléchie et une partie réfractée. Les angles se mesurent par rapport à la normale à la surface.', 'La réfraction change de direction car la lumière ne se propage pas à la même vitesse dans les deux milieux.'], formula: { label: 'LOI DE SNELL-DESCARTES', text: 'n₁ sin(i₁) = n₂ sin(i₂)' }, example: { statement: 'Un rayon passe de l’air (n₁ = 1) au verre (n₂ = 1,5) avec i₁ = 30°. Calculer i₂.', calculation: 'sin(i₂) = (1/1,5) sin(30°) = 1/3.', answer: 'i₂ ≈ 19,5°.' }, exercise: { question: 'La lumière passe de l’eau vers l’air. Se rapproche-t-elle ou s’éloigne-t-elle de la normale ?', answer: 'Elle s’éloigne de la normale, car l’indice diminue.' } } },
      { id: 'optique-ondulatoire', title: 'Optique ondulatoire et polarisation', field: 'Optique · approfondissement', summary: 'Interférences lumineuses, diffraction et polarisation.', lesson: { sections: ['La lumière présente aussi un comportement ondulatoire. Deux sources cohérentes produisent des franges d’interférences dont la position dépend de la différence de marche.', 'La polarisation décrit l’orientation du champ électrique d’une onde lumineuse. Un polariseur sélectionne une direction de vibration.'], formula: { label: 'DIFFÉRENCE DE MARCHE', text: 'Constructive : δ = kλ  |  Destructive : δ = (k + ½)λ' }, example: { statement: 'La différence de marche vaut 2λ. L’interférence est-elle constructive ou destructive ?', calculation: 'δ/λ = 2 est un entier.', answer: 'L’interférence est constructive.' }, exercise: { question: 'Quelle condition donne une interférence destructive ?', answer: 'δ = (k + 1/2)λ, où k est un entier.' } } }
    ]
  },
  {
    id: 'fluides', title: 'Mécanique des fluides', note: 'Équilibre, écoulement et transport dans les fluides.',
    chapters: [
      { id: 'hydrostatique', title: 'Hydrostatique et poussée d’Archimède', field: 'Fluides · bases', summary: 'Pression dans un fluide au repos et poussée exercée sur un corps immergé.', lesson: { sections: ['Dans un fluide au repos, la pression augmente avec la profondeur. Une différence de pression entre le haut et le bas d’un objet immergé produit une force résultante vers le haut.', 'La poussée d’Archimède est égale au poids du fluide déplacé. Elle explique la flottaison des objets.'], formula: { label: 'PRESSION ET POUSSÉE D’ARCHIMÈDE', text: 'p = p₀ + ρgh  |  FA = ρfluide g Vdéplacé' }, example: { statement: 'Quel est le poids de l’eau déplacée par un objet immergé de volume 2 L ? Prendre ρ = 1000 kg·m⁻³ et g = 9,81 m·s⁻².', calculation: 'V = 0,002 m³ ; FA = 1000 × 9,81 × 0,002.', answer: 'La poussée vaut 19,62 N.' }, exercise: { question: 'Comment varie la pression quand on descend de 2 m dans l’eau ?', answer: 'Elle augmente de Δp = ρgΔh ≈ 1000×9,81×2 = 19 620 Pa.' } } },
      { id: 'bernoulli', title: 'Écoulement et théorème de Bernoulli', field: 'Fluides · intermédiaire', summary: 'Débit, conservation du débit et échange entre pression, vitesse et altitude.', lesson: { sections: ['Pour un fluide incompressible en régime permanent, le débit volumique se conserve le long d’un conduit sans fuite.', 'Le théorème de Bernoulli exprime la conservation de l’énergie mécanique par unité de volume le long d’une ligne de courant, dans les hypothèses du modèle idéal.'], formula: { label: 'CONTINUITÉ ET BERNOULLI', text: 'Q = Sv  |  p + ½ρv² + ρgz = constante' }, example: { statement: 'Un conduit passe de 4 cm² à 1 cm². Si la vitesse initiale est 1 m·s⁻¹, quelle est la vitesse dans la partie étroite ?', calculation: 'S₁v₁ = S₂v₂, donc v₂ = S₁v₁/S₂ = 4×1/1.', answer: 'v₂ = 4 m·s⁻¹.' }, exercise: { question: 'Si la section d’un conduit double et que le débit reste constant, que devient la vitesse ?', answer: 'Elle est divisée par deux puisque Q = Sv.' } } },
      { id: 'viscosite', title: 'Viscosité et régime d’écoulement', field: 'Fluides · approfondissement', summary: 'Frottements internes, écoulement laminaire ou turbulent et nombre de Reynolds.', lesson: { sections: ['La viscosité quantifie les frottements internes d’un fluide. Elle dissipe de l’énergie mécanique en chaleur et ralentit l’écoulement.', 'Le nombre de Reynolds compare les effets d’inertie aux effets visqueux. Il aide à prévoir si un écoulement est plutôt laminaire ou turbulent.'], formula: { label: 'NOMBRE DE REYNOLDS', text: 'Re = ρvL/μ' }, example: { statement: 'Calculer Re pour l’eau avec ρ = 1000 kg·m⁻³, v = 0,1 m·s⁻¹, L = 0,01 m et μ = 10⁻³ Pa·s.', calculation: 'Re = 1000×0,1×0,01/(10⁻³).', answer: 'Re = 1000.' }, exercise: { question: 'Comment varie Re si la vitesse double ?', answer: 'Re est proportionnel à v, donc il double.' } } }
    ]
  },
  {
    id: 'physique-quantique', title: 'Physique quantique et atomique', note: 'Quand l’énergie et la matière se décrivent à l’échelle microscopique.',
    chapters: [
      { id: 'photons', title: 'Photons et effet photoélectrique', field: 'Quantique · bases', summary: 'Quantification de la lumière, énergie des photons et seuil d’extraction.', lesson: { sections: ['La lumière échange de l’énergie par paquets appelés photons. L’énergie de chaque photon dépend de sa fréquence, pas de l’intensité lumineuse.', 'Dans l’effet photoélectrique, un métal émet un électron si le photon apporte au moins l’énergie d’extraction. Une fréquence seuil existe donc.'], formula: { label: 'ÉNERGIE DU PHOTON', text: 'E = hf = hc/λ' }, example: { statement: 'Calculer l’énergie d’un photon de fréquence 5×10¹⁴ Hz avec h = 6,63×10⁻³⁴ J·s.', calculation: 'E = 6,63×10⁻³⁴ × 5×10¹⁴.', answer: 'E ≈ 3,32×10⁻¹⁹ J, soit environ 2,07 eV.' }, exercise: { question: 'L’énergie d’un photon augmente-t-elle quand sa longueur d’onde diminue ?', answer: 'Oui : E = hc/λ, donc l’énergie est inversement proportionnelle à λ.' } } },
      { id: 'dualite-onde-corpuscule', title: 'Dualité onde-corpuscule et de Broglie', field: 'Quantique · intermédiaire', summary: 'Comportement ondulatoire des particules et longueur d’onde associée.', lesson: { sections: ['La dualité onde-corpuscule associe des propriétés ondulatoires aux particules et des propriétés corpusculaires à la lumière.', 'La longueur d’onde de de Broglie est d’autant plus courte que la quantité de mouvement est grande ; les effets ondulatoires sont surtout visibles à petite échelle.'], formula: { label: 'LONGUEUR D’ONDE DE DE BROGLIE', text: 'λ = h/p' }, example: { statement: 'Comment évolue λ si la quantité de mouvement p est multipliée par 4 ?', calculation: 'La relation λ = h/p montre que la longueur d’onde est inversement proportionnelle à p.', answer: 'λ est divisée par 4.' }, exercise: { question: 'Que devient la longueur d’onde associée à une particule immobile ?', answer: 'Dans le modèle non relativiste, p tend vers 0 et λ = h/p devient très grande ; une particule localisée ne peut toutefois pas être exactement immobile.' } } },
      { id: 'atomes-niveaux', title: 'Atomes et niveaux d’énergie', field: 'Quantique · intermédiaire', summary: 'États quantifiés, transitions et spectres d’émission ou d’absorption.', lesson: { sections: ['Dans un atome, les électrons ne peuvent occuper que certains états d’énergie. Une transition entre deux niveaux s’accompagne de l’émission ou de l’absorption d’un photon.', 'La fréquence de la lumière émise dépend de l’écart d’énergie entre les deux niveaux ; le spectre sert ainsi de signature aux éléments.'], formula: { label: 'TRANSITION ÉNERGÉTIQUE', text: '|ΔE| = hf = hc/λ' }, example: { statement: 'Un atome émet un photon lors d’une transition de 3,0 eV. Quelle est sa longueur d’onde approximative ?', calculation: 'λ ≈ 1240 eV·nm / 3,0 eV.', answer: 'λ ≈ 413 nm.' }, exercise: { question: 'Lors d’une émission, l’énergie de l’atome augmente-t-elle ou diminue-t-elle ?', answer: 'Elle diminue de l’énergie emportée par le photon.' } } }
    ]
  },
  {
    id: 'physique-nucleaire', title: 'Physique nucléaire et particules', note: 'Noyaux, radioactivité, réactions et constituants de la matière.',
    chapters: [
      { id: 'radioactivite', title: 'Radioactivité et décroissance', field: 'Nucléaire · bases', summary: 'Désintégration spontanée, demi-vie et loi de décroissance radioactive.', lesson: { sections: ['La désintégration radioactive est aléatoire pour un noyau isolé, mais prévisible statistiquement pour un grand ensemble de noyaux.', 'La demi-vie est la durée au bout de laquelle la moitié des noyaux radioactifs initiaux se sont désintégrés.'], formula: { label: 'LOI DE DÉCROISSANCE', text: 'N(t) = N₀e^(−λt)  |  t₁/₂ = ln(2)/λ' }, example: { statement: 'Un échantillon contient 800 noyaux radioactifs. Combien en reste-t-il après deux demi-vies ?', calculation: 'Après chaque demi-vie, la quantité est divisée par deux : 800 → 400 → 200.', answer: 'Il reste en moyenne 200 noyaux.' }, exercise: { question: 'Quelle fraction reste après trois demi-vies ?', answer: 'Il reste (1/2)³ = 1/8 de la quantité initiale.' } } },
      { id: 'energie-nucleaire', title: 'Énergie de liaison et réactions nucléaires', field: 'Nucléaire · intermédiaire', summary: 'Défaut de masse, énergie de liaison, fission et fusion.', lesson: { sections: ['La masse d’un noyau lié est inférieure à la somme des masses de ses nucléons libres. La différence correspond à l’énergie de liaison.', 'Lors d’une réaction nucléaire, la différence de masse entre états initial et final se transforme en énergie. Une réaction libère de l’énergie si les produits sont plus liés.'], formula: { label: 'ÉQUIVALENCE MASSE-ÉNERGIE', text: 'E = Δmc²' }, example: { statement: 'Une réaction présente un défaut de masse de 1,0×10⁻²⁹ kg. Estimer l’énergie libérée.', calculation: 'E = Δmc² ≈ 1,0×10⁻²⁹ × (3,0×10⁸)².', answer: 'E ≈ 9,0×10⁻¹³ J.' }, exercise: { question: 'Pourquoi une petite perte de masse peut-elle libérer beaucoup d’énergie ?', answer: 'Parce que l’énergie vaut Δmc² et que c² est très grand.' } } },
      { id: 'particules-elementaires', title: 'Particules élémentaires', field: 'Nucléaire · approfondissement', summary: 'Quarks, leptons, interactions fondamentales et antimatière.', lesson: { sections: ['Le modèle standard décrit les particules élémentaires connues et trois interactions fondamentales : électromagnétique, faible et forte. La gravitation n’y est pas intégrée.', 'Les protons et neutrons sont composés de quarks liés par l’interaction forte ; les électrons appartiennent à la famille des leptons.'], formula: { label: 'CONTENU DU PROTON', text: 'Proton : uud  |  Neutron : udd' }, example: { statement: 'Quelle est la charge électrique totale des quarks d’un proton ?', calculation: 'Deux quarks u portent chacun +2/3 e et un quark d porte −1/3 e.', answer: '2×(2/3)e − (1/3)e = +e.' }, exercise: { question: 'Quelle est la charge totale des quarks d’un neutron udd ?', answer: '(2/3)e − (1/3)e − (1/3)e = 0.' } } }
    ]
  },
  {
    id: 'relativite', title: 'Relativité', note: 'Espace, temps, mouvement rapide et gravitation.',
    chapters: [
      { id: 'relativite-restreinte', title: 'Relativité restreinte', field: 'Relativité · bases', summary: 'Référentiels inertiels, invariance de la vitesse de la lumière et dilatation du temps.', lesson: { sections: ['La relativité restreinte repose sur deux idées : les lois de la physique ont la même forme dans les référentiels inertiels, et la vitesse de la lumière dans le vide est la même pour tous les observateurs inertiels.', 'Le temps mesuré entre deux événements dépend du mouvement de l’observateur. La différence devient importante lorsque la vitesse approche celle de la lumière.'], formula: { label: 'FACTEUR DE LORENTZ', text: 'γ = 1/√(1 − v²/c²)' }, example: { statement: 'Calculer γ pour un objet se déplaçant à 0,6c.', calculation: 'γ = 1/√(1 − 0,36) = 1/0,8.', answer: 'γ = 1,25.' }, exercise: { question: 'Que vaut γ lorsque v est très petit devant c ?', answer: 'v²/c² est négligeable, donc γ ≈ 1 : on retrouve l’approximation classique.' } } },
      { id: 'espace-temps', title: 'Espace-temps et causalité', field: 'Relativité · intermédiaire', summary: 'Événements, intervalles relativistes, cônes de lumière et simultanéité.', lesson: { sections: ['Un événement est repéré par trois coordonnées spatiales et une date. Deux observateurs en mouvement relatif ne s’accordent pas nécessairement sur la simultanéité d’événements éloignés.', 'La causalité reste protégée : aucun signal ne peut transmettre une information plus vite que la lumière.'], formula: { label: 'INTERVALLE D’ESPACE-TEMPS', text: 's² = c²Δt² − Δx² − Δy² − Δz²' }, example: { statement: 'Deux événements sont séparés de Δt = 2 μs et Δx = 300 m dans une dimension. Calculer l’intervalle s².', calculation: 'cΔt = 3×10⁸ × 2×10⁻⁶ = 600 m. Donc s² = 600² − 300².', answer: 's² = 270 000 m² : la séparation est de type temps.' }, exercise: { question: 'Peut-on relier causalement deux événements séparés par une distance supérieure à cΔt ?', answer: 'Non, il faudrait un signal plus rapide que la lumière.' } } },
      { id: 'relativite-generale', title: 'Relativité générale et gravitation', field: 'Relativité · approfondissement', summary: 'Principe d’équivalence, courbure de l’espace-temps et gravitation.', lesson: { sections: ['La relativité générale interprète la gravitation comme un effet de la géométrie de l’espace-temps. La matière et l’énergie modifient cette géométrie ; les corps suivent les trajectoires naturelles de cet espace-temps courbe.', 'Le principe d’équivalence relie localement les effets d’un champ gravitationnel à ceux d’une accélération.'], formula: { label: 'LIMITE NEWTONIENNE', text: 'g = GM/r²' }, example: { statement: 'Comment varie l’accélération gravitationnelle si la distance au centre d’un astre double ?', calculation: 'g est proportionnelle à 1/r² ; remplacer r par 2r divise g par 2².', answer: 'Elle est divisée par 4.' }, exercise: { question: 'À quoi correspond localement l’apesanteur d’un astronaute en orbite ?', answer: 'L’astronaute et le vaisseau sont en chute libre commune ; il ne ressent donc pas de force de soutien.' } } }
    ]
  },
  {
    id: 'matiere-condensee', title: 'Matière condensée et matériaux', note: 'Organisation microscopique des solides et propriétés émergentes.',
    chapters: [
      { id: 'structures-cristallines', title: 'Structures cristallines', field: 'Matériaux · bases', summary: 'Réseaux périodiques, maille, compacité et diffraction des rayons X.', lesson: { sections: ['Un cristal est organisé selon une structure périodique. Une maille élémentaire, répétée dans l’espace, décrit le réseau et les positions des atomes.', 'La diffraction des rayons X révèle les distances interatomiques, car la longueur d’onde des rayons X est du même ordre de grandeur.'], formula: { label: 'LOI DE BRAGG', text: '2d sin(θ) = nλ' }, example: { statement: 'Pour n = 1, λ = 0,20 nm et θ = 30°, calculer l’espacement d.', calculation: 'd = λ/(2sinθ) = 0,20/(2×0,5).', answer: 'd = 0,20 nm.' }, exercise: { question: 'Que devient l’angle de diffraction si λ et d restent constants mais que l’ordre n augmente ?', answer: 'sinθ augmente, donc l’angle θ augmente tant que la diffraction est possible.' } } },
      { id: 'bandes-energie', title: 'Bandes d’énergie et matériaux', field: 'Matériaux · intermédiaire', summary: 'Bandes de valence et de conduction, isolants, conducteurs et semi-conducteurs.', lesson: { sections: ['Dans un solide, les niveaux d’énergie des atomes se regroupent en bandes. La bande de valence contient les électrons liés ; la bande de conduction permet le transport électrique.', 'La taille de la bande interdite distingue notamment conducteurs, semi-conducteurs et isolants. La température ou le dopage peuvent modifier la conductivité d’un semi-conducteur.'], formula: { label: 'ÉNERGIE DU PHOTON', text: 'E = hf ; absorption possible si E ≥ Eg' }, example: { statement: 'Un semi-conducteur a une bande interdite Eg = 1,1 eV. Un photon de 2 eV peut-il créer une excitation ?', calculation: 'L’énergie du photon dépasse la bande interdite : 2 eV > 1,1 eV.', answer: 'Oui, il peut promouvoir un électron vers la bande de conduction.' }, exercise: { question: 'Pourquoi un métal conduit-il bien l’électricité ?', answer: 'Il possède des états électroniques disponibles proches en énergie, permettant aux électrons de se déplacer sous l’action d’un champ.' } } },
      { id: 'supraconductivite', title: 'Magnétisme et supraconductivité', field: 'Matériaux · approfondissement', summary: 'Réponse magnétique des matériaux et transport sans résistance.', lesson: { sections: ['Les matériaux répondent différemment à un champ magnétique selon leur structure microscopique. La susceptibilité caractérise cette réponse.', 'Sous une température critique, certains matériaux deviennent supraconducteurs : leur résistance électrique disparaît et ils expulsent le champ magnétique de leur volume, effet Meissner.'], formula: { label: 'RÉSISTANCE EN ÉTAT SUPRACONDUCTEUR', text: 'T < Tc  ⇒  R = 0 (dans le modèle idéal)' }, example: { statement: 'Un fil supraconducteur maintient un courant sans source de tension dans le modèle idéal. Quelle est la puissance Joule ?', calculation: 'P = RI². Si R = 0, alors P = 0.', answer: 'La dissipation Joule est nulle.' }, exercise: { question: 'La supraconductivité apparaît-elle à toute température ?', answer: 'Non, elle apparaît sous une température critique propre au matériau.' } } }
    ]
  },
  {
    id: 'astrophysique', title: 'Astrophysique et cosmologie', note: 'Des systèmes planétaires à l’évolution de l’Univers.',
    chapters: [
      { id: 'gravitation-orbites', title: 'Gravitation et mécanique orbitale', field: 'Astrophysique · bases', summary: 'Force gravitationnelle, orbites circulaires et lois de Kepler.', lesson: { sections: ['La gravitation est une interaction attractive entre deux masses. Pour un satellite en orbite circulaire, la force gravitationnelle fournit l’accélération centripète.', 'Les lois de Kepler décrivent les orbites planétaires ; pour des orbites autour du même astre, le carré de la période est proportionnel au cube du demi-grand axe.'], formula: { label: 'GRAVITATION ET TROISIÈME LOI DE KEPLER', text: 'F = GMm/r²  |  T²/a³ = constante' }, example: { statement: 'Un satellite orbite à une distance r du centre. Comment varie sa vitesse circulaire si le rayon orbital est multiplié par 4 ?', calculation: 'v = √(GM/r). Remplacer r par 4r divise la vitesse par √4.', answer: 'La vitesse est divisée par 2.' }, exercise: { question: 'Quelle force maintient une planète sur son orbite autour du Soleil ?', answer: 'La force gravitationnelle exercée par le Soleil.' } } },
      { id: 'etoiles', title: 'Étoiles et évolution stellaire', field: 'Astrophysique · intermédiaire', summary: 'Équilibre hydrostatique, fusion nucléaire et étapes de vie des étoiles.', lesson: { sections: ['Une étoile est une boule de plasma maintenue par la gravitation et chauffée par les réactions nucléaires de son cœur. L’équilibre hydrostatique oppose la pression interne à la gravité.', 'La masse initiale détermine largement l’évolution : les étoiles peu massives finissent en naines blanches, les plus massives peuvent exploser en supernova.'], formula: { label: 'LUMINOSITÉ ET FLUX', text: 'F = L/(4πd²)' }, example: { statement: 'À quelle fraction du flux initial s’attend-on si la distance à une étoile double ?', calculation: 'Le flux varie comme 1/d² ; pour 2d, il est divisé par 4.', answer: 'Le flux reçu vaut un quart du flux initial.' }, exercise: { question: 'Quel mécanisme fournit l’énergie d’une étoile de la séquence principale ?', answer: 'La fusion nucléaire, principalement la fusion de l’hydrogène en hélium.' } } },
      { id: 'cosmologie', title: 'Galaxies et expansion de l’Univers', field: 'Cosmologie · approfondissement', summary: 'Décalage vers le rouge, expansion cosmique et histoire de l’Univers.', lesson: { sections: ['À grande échelle, les galaxies s’éloignent les unes des autres dans un Univers en expansion. Le décalage vers le rouge de leur lumière renseigne sur leur vitesse d’éloignement.', 'La loi de Hubble-Lemaître relie approximativement la vitesse d’éloignement à la distance pour les galaxies proches à l’échelle cosmologique.'], formula: { label: 'LOI DE HUBBLE-Lemaître', text: 'v ≈ H₀d' }, example: { statement: 'Avec H₀ = 70 km·s⁻¹·Mpc⁻¹, estimer la vitesse d’éloignement d’une galaxie située à 10 Mpc.', calculation: 'v ≈ 70 × 10.', answer: 'v ≈ 700 km·s⁻¹.' }, exercise: { question: 'Dans ce modèle, que devient la vitesse si la distance double ?', answer: 'Elle double, car v est proportionnelle à d.' } } }
    ]
  },
  {
    id: 'mesures-methodes', title: 'Mesures, unités et méthodes expérimentales', note: 'Les outils transversaux pour quantifier et confronter les modèles au réel.',
    chapters: [
      { id: 'unites-dimensions', title: 'Unités et analyse dimensionnelle', field: 'Méthodes · bases', summary: 'Système international, dimensions et vérification d’équations physiques.', lesson: { sections: ['Une grandeur physique s’exprime avec une valeur numérique et une unité. L’analyse dimensionnelle vérifie que les deux membres d’une relation ont les mêmes dimensions.', 'Elle permet de repérer une erreur d’unité ou de construire une forme possible pour une loi, mais ne suffit pas à déterminer ses constantes numériques.'], formula: { label: 'DIMENSIONS FONDAMENTALES', text: '[v] = L·T⁻¹  |  [a] = L·T⁻²  |  [F] = M·L·T⁻²' }, example: { statement: 'La formule v = d/t est-elle homogène ?', calculation: '[d/t] = L/T, qui est bien la dimension d’une vitesse.', answer: 'Oui, la relation est dimensionnellement homogène.' }, exercise: { question: 'L’expression d = vt + ½at² est-elle homogène ?', answer: 'vt a la dimension L ; at² vaut aussi L. Les deux termes sont des longueurs.' } } },
      { id: 'incertitudes', title: 'Incertitudes et chiffres significatifs', field: 'Méthodes · intermédiaire', summary: 'Précision des mesures, incertitude absolue et relative, propagation.', lesson: { sections: ['Une mesure expérimentale n’est jamais parfaitement exacte. On décrit sa précision par une incertitude, qui dépend de l’instrument et du protocole.', 'L’incertitude relative compare l’incertitude absolue à la valeur mesurée. Elle permet de comparer la qualité de mesures de tailles différentes.'], formula: { label: 'INCERTITUDE RELATIVE', text: 'uᵣ(x) = u(x)/|x|' }, example: { statement: 'Une longueur est mesurée à 20,0 ± 0,2 cm. Calculer l’incertitude relative.', calculation: 'uᵣ = 0,2/20,0 = 0,01.', answer: 'L’incertitude relative est 1 %.' }, exercise: { question: 'Une masse de 50 g est connue à ±1 g. Quelle est l’incertitude relative ?', answer: '1/50 = 0,02, soit 2 %.' } } },
      { id: 'experimentation-modelisation', title: 'Expérimentation et modélisation', field: 'Méthodes · pratique', summary: 'Protocole, variables, ajustement de données et validation d’un modèle.', lesson: { sections: ['Une expérience scientifique précise une question, les grandeurs mesurées, les variables contrôlées et le protocole. Répéter les mesures aide à estimer la dispersion.', 'Un modèle propose une relation mathématique entre grandeurs. On le confronte aux observations en examinant les résidus, les incertitudes et son domaine de validité.'], formula: { label: 'RÉSIDU D’UN MODÈLE', text: 'résidu = valeur mesurée − valeur prédite' }, example: { statement: 'Un modèle prédit 9,8 m·s⁻² et une mesure donne 9,7 m·s⁻². Quel est le résidu ?', calculation: 'r = 9,7 − 9,8.', answer: 'Le résidu vaut −0,1 m·s⁻².' }, exercise: { question: 'Pourquoi répéter une mesure plusieurs fois ?', answer: 'Pour estimer la variabilité expérimentale et réduire l’influence d’une erreur aléatoire.' } } }
    ]
  }
];
